"""Add hf_enriched and reference_link to Question

Revision ID: 230ddf9265d2
Revises: e1f2g3h4i5j6
Create Date: 2026-04-06 16:00:50.341542

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '230ddf9265d2'
down_revision = 'e1f2g3h4i5j6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hf_enriched', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reference_link', sa.Text(), nullable=True))

    with op.batch_alter_table('study_buddy_messages', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('tutor_reviews', schema=None) as batch_op:
        batch_op.alter_column('tutor_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_reviews', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('tutor_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('study_buddy_messages', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('reference_link')
        batch_op.drop_column('hf_enriched')

    # ### end Alembic commands ###
