"""add key_concepts to document_sections and concepts to questions

Revision ID: 72d65b5ee98a
Revises: b3a836608fa7
Create Date: 2026-04-07 09:50:43.731049

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = '72d65b5ee98a'
down_revision = 'b3a836608fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_concepts', sa.JSON(), nullable=True))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('concepts', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_text', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('concepts')

    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.drop_column('key_concepts')

    # ### end Alembic commands ###
