"""add_leagues

Revision ID: 7f8391c6374a
Revises: 72d65b5ee98a
Create Date: 2026-04-07 11:01:24.803631

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = '7f8391c6374a'
down_revision = '72d65b5ee98a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('season_id', sa.String(length=50), nullable=True),
    sa.Column('room_number', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('league_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['league_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id')
    )
    # with op.batch_alter_table('questions', schema=None) as batch_op:
    #     batch_op.alter_column('embedding',
    #            existing_type=sa.TEXT(),
    #            type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
    #            existing_nullable=True)
    #     batch_op.drop_column('embedding_text')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('league_tier', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('league_tier')
        batch_op.drop_column('league_points')

    # with op.batch_alter_table('questions', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('embedding_text', sa.TEXT(), autoincrement=False, nullable=True))
    #     batch_op.alter_column('embedding',
    #            existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)

    op.drop_table('league_members')
    op.drop_table('league_rooms')
    # ### end Alembic commands ###
