"""challenge expires_at and buddy constraints

Revision ID: a7d7238bbd2b
Revises: h2c3d4e5f6g7
Create Date: 2026-04-11 13:29:05.950070

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = 'a7d7238bbd2b'
down_revision = 'h2c3d4e5f6g7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_action'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_admin_id'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_created_at'))

    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('question_option_explanations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_option_explanations_selected_option'))

    # pgvector not supported on this system
    # with op.batch_alter_table('questions', schema=None) as batch_op:
    #     batch_op.alter_column('embedding',
    #            existing_type=sa.TEXT(),
    #            type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
    #            existing_nullable=True)
    #     batch_op.drop_column('embedding_text')


    with op.batch_alter_table('study_buddies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('study_buddies_user_id_buddy_id_key'), type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('bio_visibility',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'public'::character varying"))
        batch_op.alter_column('bio_moderation_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'approved'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('bio_moderation_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'approved'::character varying"))
        batch_op.alter_column('bio_visibility',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'public'::character varying"))

    with op.batch_alter_table('study_buddies', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('study_buddies_user_id_buddy_id_key'), ['user_id', 'buddy_id'], postgresql_nulls_not_distinct=False)

    # with op.batch_alter_table('questions', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('embedding_text', sa.TEXT(), autoincrement=False, nullable=True))
    #     batch_op.alter_column('embedding',
    #            existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)


    with op.batch_alter_table('question_option_explanations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_option_explanations_selected_option'), ['selected_option'], unique=False)

    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_action'), ['action'], unique=False)

    # ### end Alembic commands ###
