"""add_section_status

Revision ID: b3a836608fa7
Revises: 360800b73415
Create Date: 2026-04-07 00:17:39.158087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a836608fa7'
down_revision = '360800b73415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.drop_column('status')
    # ### end Alembic commands ###
